version: "3.9"

services:
  vllm-manager:
    build: .
    image: serverllm-manager:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - MODELS_ROOT=/models
      - FLASK_PORT=5000
    volumes:
      - ./models:/models
      - ./hf-cache:/root/.cache/huggingface
    shm_size: "16g"
